### ISSUE TITLE
Repository isn't tagged with version

### ISSUE THREAD

**Issue by yurivict** [PASSIONLab/CombBLAS#13]
CMakeLists.txt has version 1.16.0.
https://people.eecs.berkeley.edu/~aydin/CombBLAS_FILES/ has 1.6.2

Whats is the version of this project?

**Comment by aydinbuluc** [comment]
https://people.eecs.berkeley.edu/~aydin/CombBLAS_FILES/ files are historical. 
We haven't been doing official releases on github but it is probably time that we do a 2.0 release here

**Comment by aydinbuluc** [comment]
Did a 2.0 release.
