### ISSUE TITLE
Possible typo in Applications' makefile

### ISSUE THREAD

**Issue by kaansancak** [PASSIONLab/CombBLAS#3]
Should [this line](https://github.com/PASSIONLab/CombBLAS/blob/master/Applications/makefile-nersc#L49) be changed as the following `$(COMPILER) $(INCADD) $(FLAGS) -c -o mmio.o $(COMBBLAS_SRC)/mmio.c`?

I couldn't get it compiled otherwise.

**Comment by aydinbuluc** [comment]
I don't think so. Which architecture are your trying to compile?

**Comment by kaansancak** [comment]
I am trying to compile `CC.cpp` via `make cc` on  Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz with gcc/8.3.0 and  mvapich2/2.3.2

**Comment by aydinbuluc** [comment]
This particular makefile is only to be used in NERSC (https://www.nersc.gov/) so it is tailored for that. At NERSC, mmio.c can not be compiled by a C++ compiler (which CC is) and needs a pure C compiler (which cc is). If your modifications to the makefile make the code compilable on your machine, then it is great. But it isn't a typo.

Cheers,
- Aydin

**Comment by kaansancak** [comment]
> This particular makefile is only to be used in NERSC (https://www.nersc.gov/) so it is tailored for that. At NERSC, mmio.c can not be compiled by a C++ compiler (which CC is) and needs a pure C compiler (which cc is). If your modifications to the makefile make the code compilable on your machine, then it is great. But it isn't a typo.
> 
> Cheers,
> 
> * Aydin

Thanks for the explanation.

Regards,
Kaan
